stages:
  - build
  - deploy

# Build stage: Compile the Next.js app and export static files
build:
  stage: build
  image: node:18-alpine
  script:
    - npm install
    - npm run build # Includes next export
  artifacts:
    paths:
      - out/
      - public/
    expire_in: 1 hour
  only:
    - main

# Deploy stage: Move files to public and update SSL certificates
deploy_ssl_and_static:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git openssl
    - git config --global user.name "kevinjam"
    - git config --global user.email "kevin.janvier5@gmail.com"
    - git fetch origin main
    - git checkout main
  script:
    - mkdir -p public/ssl
    - echo "$CF_CERTIFICATE" > public/ssl/cert.pem
    - echo "$CF_PRIVATE_KEY" > public/ssl/key.pem
    - mv public public_backup
    - mkdir -p public
    - mv public_backup/ssl public/
    - mv public_backup/sw.js public/ 2>/dev/null || true
    - if [ -d "out" ] && [ "$(ls -A out)" ]; then mv out/* public/; else echo "out/ directory is empty or does not exist"; exit 1; fi
    - rm -rf public_backup
    - git add public/
    - git commit -m "Deploy Next.js static site and update SSL certificate"
    - git push origin main
  dependencies:
    - build
  only:
    - main
  environment:
    name: production