pages:
  stage: deploy
  script:
    - if [ ! -d public ]; then mkdir public; fi
    - cp -r * public/
  artifacts:
    paths:
      - public
  only:
    - main  # Or master, depending on your default branch
