pages:
  stage: deploy
  script:
    - if [ ! -d public ]; then mkdir public; fi
    - find . -maxdepth 1 -mindepth 1 -not -name public -exec cp -r {} public/ \;
  artifacts:
    paths:
      - public
  only:
    - main  # Or master, depending on your default branch
