# pages:
#   stage: deploy
#   script:
#     - if [ ! -d public ]; then mkdir public; fi
#     - find . -maxdepth 1 -mindepth 1 -not -name public -exec cp -r {} public/ \;
  # artifacts:
  #   paths:
  #     - public
#   only:
#     - main  # Or master, depending on your default branch
stages:
  - deploy

deploy_ssl:
  stage: deploy
  image: alpine:latest
  script:
    # Create a directory for the SSL certificate
    - mkdir -p public/ssl
    # Save the certificate and key
    - echo "$CF_CERTIFICATE" > public/ssl/cert.pem
    - echo "$CF_PRIVATE_KEY" > public/ssl/key.pem
    # Add the files to the Git repository
    - git config --global user.name "kevinjam"
    - git config --global user.email "kevin.janvier5@gmail.com"
    - git add public/ssl/cert.pem public/ssl/key.pem
    - git commit -m "Update SSL certificate"
    - git push origin main

  artifacts:
    paths:
      - public    
  only:
    - main


